---
install:
  - bundle install

build: off

test_script:
  - rake

on_finish:
  - ruby -v

deploy: off

environment:
  NOBENCHMARK: 1
  matrix:
    - ruby_version: 22
    - ruby_version: 22-x64
    - ruby_version: 23
    - ruby_version: 23-x64
    - ruby_version: 24
    - ruby_version: 24-x64
    - ruby_version: 25
    - ruby_version: 25-x64
    - ruby_version: _trunk
