name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Download test readline
      run: |
        sh ./download-test_readline.sh
    - name: Run test
      run: |
        rake ci-test
