name: ubuntu with readline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 'ruby-head' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Download test readline
      run: ruby download-test_readline.rb
    - name: rake test
      run: bundle exec rake test
    - name: rake ci-test
      env:
        TEST_READLINE_OR_RELINE: Reline
      run: bundle exec rake ci-test
