name: ubuntu with irb

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 'ruby-head' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Install reline
      run: |
        rake build
        rake install
    - name: Download ruby/irb
      run: |
        git clone https://github.com/ruby/irb
    - name: Setup ruby/irb
      run: |
        cd irb
        bundle install
    - name: Run irb test
      run: bundle exec rake test
