name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '9.9.x', '2.7.x', '2.6.x', '2.5.x' ]
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        if: matrix.ruby != '9.9.x'
        run: |
          gem install bundler --no-document --conservative
          bundle install
      - name: rake test
        run:  rake test
