name: windows with readline

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mingw, mswin ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: MSP-Greg/actions-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Download test readline
        run:  ./download-test_readline.ps1
      - name: rake test
        run:  rake test
      - name: rake ci-test
        run:  rake ci-test
