name: CI
on:
  push:
    branches:
      - master
      - add-support-ci-in-github_actions
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu:
    name: Run on ubuntu
    runs-on: ubuntu-latest
    strategy:
      include:
        - rvm: ruby-head
    steps:
      - run: |
        gem update --system
        gem update bundler
        sh ./download-test_readline.sh
        bundle exec rake ci-test
